// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7nAXKCNS5xpHuhdoWJCCv9T55KXzkHXM',
    appId: '1:954035696925:web:64a73b710a3aff27d89df4',
    messagingSenderId: '954035696925',
    projectId: 'jewel-b2dcd',
    authDomain: 'jewel-b2dcd.firebaseapp.com',
    storageBucket: 'jewel-b2dcd.firebasestorage.app',
    measurementId: 'G-KE5DY2P8T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt53X4LZ1NCFb-lFeHuxCKm3iEqzJkLlM',
    appId: '1:954035696925:android:04545e70c33dd07cd89df4',
    messagingSenderId: '954035696925',
    projectId: 'jewel-b2dcd',
    storageBucket: 'jewel-b2dcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh4SLXX0QaJMLmhCQdeqs4BcZ3WmbJQVg',
    appId: '1:954035696925:ios:350759e2cf003472d89df4',
    messagingSenderId: '954035696925',
    projectId: 'jewel-b2dcd',
    storageBucket: 'jewel-b2dcd.firebasestorage.app',
    androidClientId: '954035696925-2v1n6ep4v89rl58mju2ol9a23k7i4qdi.apps.googleusercontent.com',
    iosClientId: '954035696925-lccrf4i2o0je8ab7afva92uo5n1q0oqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.jewel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh4SLXX0QaJMLmhCQdeqs4BcZ3WmbJQVg',
    appId: '1:954035696925:ios:350759e2cf003472d89df4',
    messagingSenderId: '954035696925',
    projectId: 'jewel-b2dcd',
    storageBucket: 'jewel-b2dcd.firebasestorage.app',
    androidClientId: '954035696925-2v1n6ep4v89rl58mju2ol9a23k7i4qdi.apps.googleusercontent.com',
    iosClientId: '954035696925-lccrf4i2o0je8ab7afva92uo5n1q0oqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.jewel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7nAXKCNS5xpHuhdoWJCCv9T55KXzkHXM',
    appId: '1:954035696925:web:4e2d1adf45c8af00d89df4',
    messagingSenderId: '954035696925',
    projectId: 'jewel-b2dcd',
    authDomain: 'jewel-b2dcd.firebaseapp.com',
    storageBucket: 'jewel-b2dcd.firebasestorage.app',
    measurementId: 'G-C635Z97X9N',
  );

}