# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- max_backlog

pool: 
  name: Default

steps:

- task: FlutterTest@0
  inputs:
    projectDirectory: 'C:\repos\Project-Emerald\jewel'
    testName: 'testWidgets'
    testPlainName: 'default test'
    extraArgs: '--no-test-assets'
    generateCodeCoverageReport: true
    concurrency: '1'