name: DockerDeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build and tag the Docker image
  #     run: docker build . --file Dockerfile --tag jewel:latest

  push:
    runs-on: ubuntu-latest

    steps:
    - name: Azure CLI Login Init
      uses: Azure/login@v2.2.0
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI Login Verify
      run: az account show
    - name: Azure CR Login
      run: az acr login --name jewelcontainers
      
      
      
